### ISSUE TITLE
Odd data problem

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#88] opened 2016-11-11 17:29 UTC
http://128.97.229.160/rollcall/RH0770074 throws an error, but seems like it should be there...

<img width="885" alt="screen shot 2016-11-11 at 9 33 16 am" src="https://cloud.githubusercontent.com/assets/4761445/20224164/fa086b42-a7f1-11e6-9fe3-caa566da3ba3.png">

**Comment by adamboche** [comment] 2016-11-11 17:36
It seems to be there in the db. db.voteview_rollcalls.findOne({id:
'RH0770074'})

**Comment by aaronrudkin** [comment] 2016-11-14 04:43
Found the cause in the list of votes:

```
		{
			"icpsr" : 1204,
			"cast_code" : 7,
			"prob" : "N/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/A"
		},
```

It should not surprise you that the vote probability field, uh, was causing some issues.

Mitigation: Better error handling on invalid probabilities, implemented.

Todo: See why Luke's probability generation code generated whatever that is and prevent it from happening.

**Comment by lukesonnet** [comment] 2016-11-14 08:01
That seems like a pretty rough error. Sorry I was working on adding the
code that generated the probability of voting with party if they were
absent (that was stalled because the party vote call needed to be tweaked)
when I left.

My guess this is an error with checking this person's party's modal vote.

Luke Sonnet
PhD Student, Political Science
UCLA

On Nov 14, 2016 5:43 AM, "Aaron Rudkin" <notifications@github.com> wrote:

Found the cause in the list of votes:

        {
            "icpsr" : 1204,
            "cast_code" : 7,
            "prob" :
"N/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/AN/A"
        },

It should not surprise you that the vote probability field, uh, was causing
some issues.

Mitigation: Better error handling on invalid probabilities, implemented.

Todo: See why Luke's probability generation code generated whatever that is
and prevent it from happening.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JeffreyBLewis/WebVoteView/issues/88#issuecomment-260247378>,
or mute the thread

**Comment by adamboche** [comment] 2017-01-05 19:32
@JeffreyBLewis @lukesonnet

**Comment by lukesonnet** [comment] 2017-01-10 07:44
We can close this. The pre/prob code seems to be working fine.

**Closed by lukesonnet** 2017-01-10 07:44 UTC
