### ISSUE TITLE
Error in calculating date active dates for minor parties

### ISSUE THREAD

**Issue by lukesonnet** [JeffreyBLewis/WebVoteView#206] opened 2017-03-19 18:49 UTC
https://voteview.polisci.ucla.edu/parties/all

**Comment by aaronrudkin** [comment] 2017-03-20 17:53
I suspect this means at least one step of the party metadata generation is not running during automatic updates.

I will fix this in three stages:

1. Suppress the error because the text is unsightly
2. Fix the issue with the data so that we have dates
3. Investigate why this happened.

**Comment by aaronrudkin** [comment] 2017-03-20 18:13
Looks like the issue is a handful of people having invalid voting dates (or rather, voting dates being in an unexpected format), and this breaks the part of the voting date script that contours the vote date range for each party. 

@adamboche This is somewhat urgent. Looking at votes RS1070171 through RS1090062, all of the "date" fields in voteview_rollcalls are incorrect. The correct format is YYYY-mm-dd and the format given is "March 13, 2013,  01:30 PM". This is also true of a bunch of votes in RS113 as well.

**Comment by adamboche** [comment] 2017-03-20 19:43
Nice catch, @aaronrudkin.  Looks like I didn't check that for a few sessions. Those documents should be fixed now and the db will reject any further inserted documents with malformed dates.

**Comment by aaronrudkin** [comment] 2017-03-20 22:37
Super! My side of the script is also setup to not fail if they do show up.

**Closed by aaronrudkin** 2017-03-20 22:37 UTC
